export enum PAYMENT_METHOD_TYPE_ENUM {
  BANK_TRANSFER_BRI = 'BANK_TRANSFER_BRI',
  BANK_TRANSFER_BCA = 'BANK_TRANSFER_BCA',
  BANK_TRANSFER_BNI = 'BANK_TRANSFER_BNI',
  BANK_TRANSFER_MANDIRI = 'BANK_TRANSFER_MANDIRI',
  BANK_TRANSFER_PERMATA = 'BANK_TRANSFER_PERMATA',
  BANK_TRANSFER_CIMB = 'BANK_TRANSFER_CIMB',
}
